INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (100,"Fiebre Reumatica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (107,"Hepatitis Aguda Tipo B");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (114,"Hipertension");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (121,"Malestar Y Fatiga");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (128,"Nauseas Y Vomitos");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (135,"Hipertension Secundaria");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (142,"Gastroenteritis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (149,"Diarrea Funcional");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (156,"Hipertension");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (163,"Estress");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (170,"Angina De Pecho");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (177,"Neumonia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (184,"Neumonia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (191,"Fiebre Persistente");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (198,"Insuficiencia Renal Aguda");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (205,"Diarrea Funcional");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (212,"Herpes Zoster");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (219,"Estress");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (226,"Hepatitis Aguda Tipo A");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (233,"Diarrea Funcional");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (240,"Fiebre Reumatica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (247,"Hipertension Secundaria");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (254,"Fiebre Reumatica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (261,"Diarrea Funcional");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (268,"Gastroenteritis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (275,"Dermatitis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (282,"Hepatitis Aguda Tipo B");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (289,"Psoriasis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (296,"Herpes Zoster");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (303,"Estress");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (310,"Fiebre Persistente");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (317,"Hepatitis Aguda Tipo B");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (324,"Fiebre Persistente");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (331,"Obesidad");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (338,"Insuficiencia Renal Aguda");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (345,"Dermatitis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (352,"Fiebre Reumatica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (359,"Hipertension");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (366,"Estress");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (373,"Fiebre Reumatica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (380,"Anorexia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (387,"Hipertension");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (394,"Anorexia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (401,"Psoriasis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (408,"Fiebre Reumatica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (415,"Psoriasis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (422,"Obesidad");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (429,"Estress");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (436,"Neumonia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (443,"Fiebre Persistente");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (450,"Herpes Zoster");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (457,"Hepatitis Aguda Tipo B");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (464,"Obesidad");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (471,"Hipertension");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (478,"Neumonia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (485,"Hipertension");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (492,"Gastroenteritis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (499,"Hepatitis Aguda Tipo A");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (506,"Malestar Y Fatiga");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (513,"Anorexia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (520,"Estress");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (527,"Malestar Y Fatiga");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (534,"Fiebre Amarilla");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (541,"Malestar Y Fatiga");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (548,"Insuficiencia Renal Cronica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (555,"Hipertension");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (562,"Anorexia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (569,"Nauseas Y Vomitos");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (576,"Anorexia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (583,"Neumonia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (590,"Hipertension");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (597,"Gastroenteritis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (604,"Diarrea Funcional");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (611,"Insuficiencia Renal Aguda");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (618,"Fiebre Reumatica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (625,"Psoriasis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (632,"Fiebre Persistente");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (639,"Nauseas Y Vomitos");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (646,"Psoriasis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (653,"Fiebre Amarilla");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (660,"Insuficiencia Renal Cronica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (667,"Insuficiencia Renal Aguda");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (674,"Fiebre Amarilla");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (681,"Gastroenteritis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (688,"Estress");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (695,"Herpes Zoster");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (702,"Psoriasis");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (709,"Fiebre Amarilla");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (716,"Hipertension Secundaria");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (723,"Fiebre Reumatica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (730,"Obesidad");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (737,"Insuficiencia Renal Cronica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (744,"Insuficiencia Renal Aguda");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (751,"Malestar Y Fatiga");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (758,"Herpes Zoster");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (765,"Fiebre Amarilla");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (772,"Epilepsia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (779,"Fiebre Reumatica");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (786,"Anorexia");
INSERT INTO `Diagnosticos` (`codigoDiagnostico`,`descripcion`) VALUES (793,"Nauseas Y Vomitos");

-- codigo empieza 100 increment 7