insert into Drogas (nombreComercial,formula,stockMinimo,drogueria) values
("Simvastatina","C13 H18Br2N2O",1000,"Arcu Vestibulum Ante Ltd"),
("Aspirina","H2SO4",1000,"Aenean Eget Corporation"),
("Omeprazol","HNO3",1500,"Mauris Industries"),
("Lexotiroxina sódica","CH3CH2OH",1500,"Vulputate Nisi Sem Limited"),
("Ramipril","CH4",2000,"In Ornare Company"),
("Omeprazol","HNO3",2000,"Risus Quisque Libero Inc."),
("Aspirina","H2SO4",1500,"Feugiat Metus Sit Limited"),
("Amlodipina","H2O2",1000,"Tristique Aliquet Phasellus Institute"),
("Simvastatina","C13 H18Br2N2O",2000,"Eu Nulla At Industries"),
("Paracetamol","HCO3",2500,"In Faucibus Morbi Incorporated"),
("Atorvastatina","HCl",1000,"Arcu Vestibulum Ante Ltd"),
("Simvastatina","C13 H18Br2N2O",1000,"Aenean Eget Corporation"),
("Salbutamol","H2O",1500,"Mauris Industries"),
("Amlodipina","H2O2",1500,"Vulputate Nisi Sem Limited"),
("Lansoprazol","NaCl",2000,"In Ornare Company"),
("Salbutamol","H2O",1500,"Risus Quisque Libero Inc."),
("Lexotiroxina sódica","CH3CH2OH",1000,"Feugiat Metus Sit Limited"),
("Paracetamol","HCO3",1000,"Tristique Aliquet Phasellus Institute"),
("Ramipril","CH4",2000,"Eu Nulla At Industries"),
("Lansoprazol","NaCl",1500,"In Faucibus Morbi Incorporated");
